[features]
seeds = false
skip-lint = false

[programs.localnet]
winner_wheel = "971Cep8GujbgNiihvBGDmEHXry4WYb2Vxw2cbDqsb6aV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/anchor.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
gen = "anchor-client-gen target/idl/winner_wheel.json app/lib/gen"
